"""Classify checks that require the local historical evidence archive."""

import pytest

ARCHIVE_TESTS = {
    "tests/test_crash_slices.py::test_selected_pins_include_exact_controls_and_known_divergence",
    "tests/test_csv_evidence.py::test_cached_pair_reports_exact_input_and_observed_terminal_overlap",
    "tests/test_ekubo.py::test_offline_historical_pin_evidence",
    "tests/test_five_crash_liquidity.py::test_window_bounds_alignment",
    "tests/test_five_crash_liquidity.py::test_no_invented_provenance_and_saved_evidence",
    "tests/test_five_crash_liquidity.py::test_representative_check_outputs_and_policy",
    "tests/test_general_solver.py::test_v3_domain_searches_below_raw_request_and_uses_token_decimals",
    "tests/test_integration.py::test_failed_dependency_is_reported_and_excluded",
    "tests/test_integration.py::test_discovery_or_other_block_validation_does_not_admit_pool",
    "tests/test_integration.py::test_online_acquisition_rejects_changed_hash",
    "tests/test_integration.py::test_window_analysis_reports_failed_construction",
    "tests/test_integration.py::test_acquire_blocks_inactive_records_before_adapter_reads",
    "tests/test_integration.py::test_bad_read_plan_excludes_one_pool_without_aborting_other_acquisition",
    "tests/test_integration.py::test_singleton_activation_is_pinned_cached_and_does_not_guess_creation",
    "tests/test_litepsm_support.py::test_endpoint_recovery_replays_all_five_cached_pins",
    "tests/test_october_expanded_prices.py::test_candidate_floor_re_evaluation_preserves_output_and_refund",
    "tests/test_october_expanded_prices.py::test_pancake_native_vs_python_parity",
    "tests/test_october_expanded_prices.py::test_complete_routed_quote_parity",
    "tests/test_october_expansion_collect.py::test_block_range_and_references",
    "tests/test_october_expansion_collect.py::test_seed_pinned_evidence_and_supplement_context",
    "tests/test_october_expansion_collect.py::test_collected_dataset_completeness_and_manifest",
    "tests/test_october_expansion_collect.py::test_supplement_context_on_collected_dataset_across_pins",
    "tests/test_october_expansion_collect.py::test_corrupted_checkpoint_refusal",
    "tests/test_october_oracle_references.py::test_pinned_three_blocks_independent_decode",
    "tests/test_october_oracle_references.py::test_published_sidecar_contract_and_integrity",
    "tests/test_october_oracle_references.py::test_subset_run_isolation_does_not_clobber_full_artifacts",
    "tests/test_pancake_v3_historical.py::test_qualification_evidence_structure",
    "tests/test_pancake_v3_historical.py::test_historical_pins_quote_exact_matches",
    "tests/test_pancake_v3_historical.py::test_independent_replay_aggregate_summary",
    "tests/test_select_binance_crashes.py::test_generated_selection_json_contract_and_minute_files",
    "tests/test_source_expansion_integration.py::test_maker_sky_psm_delegation",
    "tests/test_source_expansion_integration.py::test_supplement_contexts_chaining",
    "tests/test_source_expansion_integration.py::test_candidate_floor_preservation_at_stress_pin",
    "tests/test_source_expansion_integration.py::test_usds_dai_usdc_exact_routing",
    "tests/test_source_expansion_integration.py::test_combined_four_overlay_universe",
    "tests/test_source_expansion_integration.py::test_combined_five_overlay_universe",
    "tests/test_source_expansion_integration.py::test_shared_psm_single_instance_no_wrapper",
    "tests/test_source_expansion_integration.py::test_offline_refusal_on_missing_data",
    "tests/test_uniswap_v3_math.py::test_tick_and_price_agree_on_every_saved_swap_event",
    "tests/test_uniswap_v3_math.py::test_compute_swap_step_reproduces_every_saved_swap_event",
    "tests/test_uniswap_v3_math.py::test_recorded_replay_summary_matches",
    "tests/test_uniswap_v3_state.py::test_types_satisfy_the_shared_protocols",
    "tests/test_uniswap_v3_state.py::test_loaded_state_matches_the_recorded_slot0",
    "tests/test_uniswap_v3_state.py::test_crash_block_state",
    "tests/test_uniswap_v3_state.py::test_state_is_immutable",
    "tests/test_uniswap_v3_state.py::test_state_rejects_holes_in_its_advertised_bitmap_window",
    "tests/test_uniswap_v3_state.py::test_consecutive_swaps_consume_shared_depth",
    "tests/test_uniswap_v3_state.py::test_quotes_match_quoter_v2_wei_exact",
    "tests/test_uniswap_v3_state.py::test_quote_exact_in_matches_swap",
    "tests/test_uniswap_v3_state.py::test_reproduces_settled_forge_fork_swaps",
    "tests/test_uniswap_v3_state.py::test_unsupported_outside_the_loaded_tick_window",
    "tests/test_uniswap_v3_state.py::test_widening_the_window_prices_a_trade_the_default_cannot",
    "tests/test_uniswap_v3_state.py::test_unsupported_for_a_pair_this_pool_does_not_hold",
    "tests/test_uniswap_v3_state.py::test_zero_and_negative_input",
    "tests/test_uniswap_v3_state.py::test_dependent_requests_rejects_failed_bitmap_read",
    "tests/test_uniswap_v3_state.py::test_dependent_requests_asks_for_bitmap_then_ticks",
    "tests/test_uniswap_v3_state.py::test_dependent_requests_converge_to_empty",
    "tests/test_uniswap_v3_state.py::test_load_state_rejects_an_unrelated_token_map",
    "tests/test_uniswap_v3_state.py::test_provenance_records_the_window",
    "tests/test_uniswap_v3_state.py::test_state_type_is_the_documented_one",
    "tests/test_usds_adapter.py::test_pinned_evidence_offline_reproduction",
    "tests/test_usds_adapter.py::test_produced_inventory_overlay_schema_regression",
    "tests/test_usds_amm.py::test_supplement_records_and_snapshots_exist",
    "tests/test_usds_amm.py::test_records_schema_and_parsing",
    "tests/test_usds_amm.py::test_pool_metadata_and_token_ordering",
    "tests/test_usds_amm.py::test_offline_pool_state_loading_across_pins",
    "tests/test_usds_amm.py::test_quoter_v2_comparison_offline",
    "tests/test_v3_continuous.py::test_cached_v3_boundary_and_integer_proposal_are_replayed_exactly",
    "tests/test_v3_continuous.py::test_five_qualified_pins_have_noninvented_loaded_domains",
    "tests/test_wbtc_collection.py::test_block_references_match_pinned_hashes",
    "tests/test_wbtc_collection.py::test_snapshots_and_records_exist",
    "tests/test_wbtc_inventory.py::test_activation_evidence_export",
    "tests/test_wbtc_routes.py::test_quoter_differential_report_exact",
    "tests/test_wbtc_routes.py::test_two_leg_full_input_consumption",
    "tests/test_wbtc_routes.py::test_offline_two_leg_eval_manifest",
}


def pytest_collection_modifyitems(items):
    for item in items:
        base_nodeid = item.nodeid.partition("[")[0]
        if base_nodeid in ARCHIVE_TESTS:
            item.add_marker(pytest.mark.archive)
